"""init2

Revision ID: 841eae42b608
Revises: 1ff7b129546e
Create Date: 2022-01-24 12:52:28.586843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841eae42b608'
down_revision = '1ff7b129546e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_index('category_category_name_ind', 'category', ['category_name'], unique=False, mysql_length=255)
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_product_category_id_category'), 'product', 'category', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_category_id_category'), 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    op.drop_index('category_category_name_ind', table_name='category', mysql_length=255)
    op.drop_table('category')
    # ### end Alembic commands ###
