"""init3

Revision ID: 39976a86bb64
Revises: 841eae42b608
Create Date: 2022-01-24 12:55:25.854392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39976a86bb64'
down_revision = '841eae42b608'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_order_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    op.create_index('order_user_id_ind', 'order', ['user_id'], unique=False, mysql_length=255)
    op.create_table('basket',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_basket_product_id_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_basket_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name=op.f('pk_basket'))
    )
    op.create_index('basket_product_id_ind', 'basket', ['product_id'], unique=False, mysql_length=255)
    op.create_index('basket_user_id_ind', 'basket', ['user_id'], unique=False, mysql_length=255)
    op.create_table('favorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_favorite_product_id_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favorite_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name=op.f('pk_favorite'))
    )
    op.create_index('favorite_product_id_ind', 'favorite', ['product_id'], unique=False, mysql_length=255)
    op.create_index('favorite_user_id_ind', 'favorite', ['user_id'], unique=False, mysql_length=255)
    op.create_table('order_detail',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_detail_order_id_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_detail_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name=op.f('pk_order_detail'))
    )
    op.create_index('order_detail_order_id_ind', 'order_detail', ['order_id'], unique=False, mysql_length=255)
    op.create_index('order_detail_product_id_ind', 'order_detail', ['product_id'], unique=False, mysql_length=255)
    op.create_table('product_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_product_comment_author_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_comment_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_comment'))
    )
    op.create_index('product_coment_author_id_ind', 'product_comment', ['author_id'], unique=False, mysql_length=255)
    op.create_index('product_coment_product_id_ind', 'product_comment', ['product_id'], unique=False, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_coment_product_id_ind', table_name='product_comment', mysql_length=255)
    op.drop_index('product_coment_author_id_ind', table_name='product_comment', mysql_length=255)
    op.drop_table('product_comment')
    op.drop_index('order_detail_product_id_ind', table_name='order_detail', mysql_length=255)
    op.drop_index('order_detail_order_id_ind', table_name='order_detail', mysql_length=255)
    op.drop_table('order_detail')
    op.drop_index('favorite_user_id_ind', table_name='favorite', mysql_length=255)
    op.drop_index('favorite_product_id_ind', table_name='favorite', mysql_length=255)
    op.drop_table('favorite')
    op.drop_index('basket_user_id_ind', table_name='basket', mysql_length=255)
    op.drop_index('basket_product_id_ind', table_name='basket', mysql_length=255)
    op.drop_table('basket')
    op.drop_index('order_user_id_ind', table_name='order', mysql_length=255)
    op.drop_table('order')
    # ### end Alembic commands ###
